# Introductory Programming with Python (Part 2)

### Loops
**Loops** allow us to repeat a block of code multiple times. This is especially useful when we have to process a collection of items, like a list of temperature readings or salinity measurements. The two primary types of loops in Python are ***for loops*** and ***while loops***.

#### For Loops:
A ***for loop*** is used to iterate over a sequence (like a list or a tuple). Here’s the basic structure:

Let’s say we want to print out each survey response score from a list:

In [2]:
survey_scores = [3, 4, 5, 2, 4]

for score in survey_scores:
    print(f"Survey score: {score} out of 5")
    
print("Last value of score:",score)

Survey score: 3 out of 5
Survey score: 4 out of 5
Survey score: 5 out of 5
Survey score: 2 out of 5
Survey score: 4 out of 5
Last value of score: 4


In [ ]:
print(survey_score[0])
print(survey_score[1])
print(survey_score[2])

In this example, the loop goes through each item in the **survey_scores** list and prints it.

For loops are useful for analyzing data, such as calculating the average monthly income from several months:

In [8]:
monthly_incomes = [3000, 3200, 3100, 2900, 4000, 3500, 2500, 2900, 3050, 3200, 3500, 2950]
total_income = 0

for income in monthly_incomes: 
    total_income += income # total_income = total_income + income

average_income = total_income / len(monthly_incomes)
print(f"Average Monthly Income: ${average_income:.2f}")

Average Monthly Income: $3150.00


In this case, the loop adds up all the monthly incomes and then finds the average by dividing by the number of months.

### Exercise

1. You are given a list named populations that contains population numbers (in thousands).
2. Use a for loop to add all the population numbers together and store the total in a variable called total_population.
3. Calculate the average population by dividing the total population.
4. Print the average population rounded to the nearest whole number.

In [9]:
populations = [2731, 631, 1135, 934, 1705]
total_population = 0

for value in populations:
    total_population += value

average_population = total_population / len(populations)
print("Average population (in thousands):", round(average_population))

Average population (in thousands): 1427


#### While Loops
A while loop continues to execute as long as a specified condition is true. The basic structure looks like this:

Let’s say we want to keep recording monthly expenses until we have data for five months:

In [13]:
monthly_expenses = []
max_months = 5

while len(monthly_expenses) < max_months:
    new_expense = float(input("Enter monthly expense amount:"))
    monthly_expenses.append(new_expense)

print("Monthly expenses collected:", monthly_expenses)

Enter monthly expense amount: 2300
Enter monthly expense amount: 3000
Enter monthly expense amount: 4500
Enter monthly expense amount: 2100
Enter monthly expense amount: 2000


Monthly expenses collected: [2300.0, 3000.0, 4500.0, 2100.0, 2000.0]


In this example, the loop keeps asking for monthly expenses until it has collected five amounts.

While loops are useful for continuous data collection, like tracking monthly donations until reaching a target amount:

In [16]:
donations = 0 

while donations < 5000:
    donations += 500
    print(f"Total Donations Collected: ${donations}")

Total Donations Collected: $500
Total Donations Collected: $1000
Total Donations Collected: $1500
Total Donations Collected: $2000
Total Donations Collected: $2500
Total Donations Collected: $3000
Total Donations Collected: $3500
Total Donations Collected: $4000
Total Donations Collected: $4500
Total Donations Collected: $5000


### Combining Loops and Conditionals
Often, we will need to use both loops and conditionals together to process data effectively. For example, you might want to analyze temperature readings and categorize them within a loop.

Let’s categorize a list of temperature readings as *"Cold," "Warm," or "Hot"*:

In [20]:
temperature_readings = [10.0, 20.5, 25.0, 30.5]

for temperature in temperature_readings:
    if temperature < 15:
        print(f"Temperature {temperature} C: Cold")
    elif 15 <= temperature <= 25:
        print(f"Temperature {temperature} C: Warm")
    else:
        print(f"Temperature {temperature} C: Hot")

Temperature 10.0 C: Cold
Temperature 20.5 C: Warm
Temperature 25.0 C: Warm
Temperature 30.5 C: Hot


In this example, the loop goes through each temperature reading, and the conditional statements categorize each temperature accordingly.

## Functions
In programming, **functions** are reusable blocks of code designed to perform a specific task. They help break down complex problems into smaller, manageable parts, making your code cleaner, easier to read, and more efficient. Functions promote the DRY (Don't Repeat Yourself) principle, which encourages code reusability.

### Defining a Function
To define a function, follow this basic syntax:

In Python, a function is defined using the ***def*** keyword followed by the function name and parentheses, which may contain *parameters*.

For example, ***def function_name(parameters):*** starts the definition, where the parameters allow you to pass input values.

A *docstring* can be included right after the function definition in triple quotes to describe the function's purpose, helping users understand its functionality. 

The main code of the function, known as the *function body*, is indented and contains the operations that the function performs. 

Finally, a *return statement* can be used to send a result back to the caller, allowing you to output a value from the function.

Here’s a simple function that adds two numbers and one that substracts them:

In [21]:
def add_numbers(a,b):
    """Returns the sum of two numbers"""
    result = a + b 
    return result

def subtract_numbers(a,b):
    """Return the subtraction of a and b"""
    return a - b 

### Calling a Function
Once a function is defined, you can call it by using its name followed by parentheses. If the function requires parameters, you need to provide them inside the parentheses.

In [23]:
result_addition = add_numbers(5,3)
result_subtraction = subtract_numbers(5,2)
print("Addition of 5 and 3:", result_addition)
print("Subtraction of 5 and 2:", result_subtraction)

Addition of 5 and 3: 8
Subtraction of 5 and 2: 3


### Parameters and Arguments
Functions can take parameters, which are placeholders for the values you pass into the function. When you call the function with actual values, those values are called arguments.

You can define functions with:

- **Positional Parameters:** These must be provided in the order defined.
- **Keyword Arguments:** These allow you to specify which parameter you're providing by name.
- **Default Parameters:** You can assign default values to parameters, which will be used if no argument is provided.


In [27]:
def greet(name, greeting = 'Hello'):
    """Greets the user with a specific greeting"""
    return f"{greeting}, {name}"

print(greet('Alice')) #Calls the function with a positional argument
print(greet('Bob', 'Hi')) # Calls the function with both positional arguments
print(greet(greeting = "Welcome", name = "Charlie")) #Calls the function using keyword arguments

Hello, Alice
Hi, Bob
Welcome, Charlie


**Explanation:**
1. ***Positional Argument:*** In print(greet("Alice")), only the positional argument is provided, so the default greeting "Hello" is used, resulting in "Hello, Alice!".

2. ***Both Positional Arguments:*** In print(greet("Bob", "Hi")), both "Bob" and "Hi" are positional arguments, where "Bob" corresponds to the name parameter and "Hi" corresponds to the greeting parameter. This results in "Hi, Bob!".

3. ***Keyword Arguments:*** In print(greet(name="Charlie", greeting="Welcome")), both arguments are specified as keyword arguments. Here, name is explicitly set to "Charlie" and greeting is set to "Welcome", resulting in "Welcome, Charlie!".



### Scope of Variables
Variables defined inside a function have local scope, meaning they cannot be accessed outside the function. Conversely, variables defined outside of a function have global scope.

In [31]:
def example_function():
    local_var = "I'm local!"
    print(local_var)

example_function()

global_var = "I'm global!"

def another_function():
   print(global_var)

another_function()

I'm local!
I'm global!


In [35]:
def return_value():
    return 5

def print_value():
    print("5")

value_1 = return_value()
value_2 = print_value()
value_1 - 3

5


2

**Explanation**

1. **Local Variable (local_var):**

- In example_function(), we define a variable called local_var inside the function. This variable is called local because it exists only within the function's scope (between the function’s def and the end of its block).
- When we run example_function(), Python prints "I'm local!" as expected.
- However, if we try to access local_var outside example_function() (for example, with print(local_var) outside the function), it will raise a NameError because local_var is not defined globally; it only exists within the function where it was created.

2. **Global Variable (global_var):**

- global_var is defined outside of any function, so it’s a global variable, accessible anywhere in the code.
- Inside another_function(), we use print(global_var). Since global_var is global, this works even though it’s outside the function.
- When we call another_function(), it prints "I'm global!" because global_var is accessible from both inside and outside the function.

### Importance of Functions
Functions help with code organization and readability. They allow you to:

- **Reuse Code:** Write a piece of code once and call it multiple times, avoiding redundancy.
- **Enhance Readability:** Break code into logical sections that describe the functionality.
- **Ease Maintenance:** Update one function instead of multiple code sections.

## Modules
In Python, a module is simply a file that contains Python code, typically functions, classes, and variables, which you can reuse in other programs. 

**Modules** help organize code, avoid repetition, and keep it easy to maintain. You can create your own module by saving a .py file with your code or use one of Python’s many built-in modules, like *math*, *datetime*, or *random*, which provide various functionalities.

### Importing Modules
To use a module in your code, you import it using the import statement. For example:

In [36]:
import math
print(math.sqrt(16))

4.0


In [37]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.12/library/math.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The re

Here, we import the math module and then use its **sqrt()** function to calculate the square root of 16.

### Importing Specific Functions
If you only need specific functions from a module, you can import them directly:

In [38]:
from math import pi, sqrt
print(pi)
print(sqrt(25))

3.141592653589793
5.0


This allows you to use pi and sqrt() directly without referencing math.

### Custom Modules
To create a custom module, you write Python code in a *.py* file. For example, if you have a file called **mymath.py** with the following content:

You can import and use these functions in another Python file as follows:

In [39]:
import mymath
print(mymath.add(3,5))
print(mymath.subtract(10,4))

8
6


### Benefits of Using Modules
- **Reusability:** Write code once and use it across multiple programs.
- **Organization:** Helps keep code organized and readable, especially for large projects.
- **Built-in Functionality:** Python’s standard library has many modules, so you don’t have to write everything from scratch.

## Introduction to Libraries

In Python, a library is a collection of modules that provide reusable code to help programmers perform various tasks without having to write everything from scratch. Libraries enhance productivity by allowing developers to leverage existing functionality for common tasks, promoting efficiency and reducing redundancy in code.

### Examples of Popular Libraries
- **NumPy:** A fundamental library for numerical computing, NumPy provides support for arrays and matrices, along with a wide range of mathematical functions.

- **Pandas:** This library is invaluable for data analysis and manipulation. It allows users to work with structured data in the form of DataFrames and Series, making it ideal for handling large datasets.

- **Matplotlib:** A powerful library for data visualization, Matplotlib enables users to create static, interactive, and animated visualizations to effectively present data insights.

Libraries are important tools in Python that help programmers work more efficiently. They provide ready-made code that can be reused, making it easier to complete common tasks without starting from scratch. By using libraries, developers can solve complicated problems more easily and concentrate on the bigger picture of their projects. 

# Numpy

NumPy, which stands for Numerical Python, is a powerful library in Python that helps with numerical and scientific computing. It allows you to work with large, multi-dimensional arrays (think of them as grids of numbers) and provides many mathematical functions to perform calculations on these arrays quickly and easily.

### Why Use NumPy?
- **Speed:** NumPy is much faster than using regular Python lists for numerical calculations. It’s written in C, which helps it run faster. When you use NumPy, you can perform operations on big sets of data quickly.

- **Convenience:** With NumPy, you can do calculations on entire arrays without writing long loops. For example, adding two arrays together can be done in just one line of code.

- **Useful Functions:** NumPy has many built-in functions for doing complex math. This is really helpful when you need to work with large amounts of data and perform a lot of calculations.

## Arrays
An **array** is a list of items stored one after another in memory. In NumPy, an array is a collection of values arranged in a grid, where all values are the same type (like all numbers or all text).

To use NumPy, we first need to import it:

In [40]:
import numpy as np 

### Creating a 1D Array
You can create a 1D array using the **np.array()** function. Here’s how:

In [41]:
# Creating a 1D array

arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

### Advantages of NumPy Arrays Over Python Lists
- **Homogeneous:** All elements in a NumPy array must be of the same type, whereas Python lists can contain mixed types.
- **Performance:** NumPy arrays are more memory efficient and faster for numerical computations compared to lists.
- **Functionality:** NumPy provides a range of built-in functions that are specifically optimized for working with arrays.

### Creating a 2D Array
To create a 2D array, pass a list of lists to **np.array()**:

In [42]:
# Creating a 2D array
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

### Creating Arrays with Built-in Functions

NumPy provides several built-in functions to create arrays quickly:

- **np.zeros(shape)**: Creates an array filled with zeros.
- **np.ones(shape)**: Creates an array filled with ones.
- **np.arange(start, stop, step)**: Creates an array with a range of values.
- **np.linspace(start, stop, num)**: Creates an array of evenly spaced numbers.

In [44]:
# Using built-in functions
zeros_array = np.zeros((2,3))
ones_array = np.ones((2,3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0,1,5)

print(zeros_array)
print("\n",ones_array)
print("\n",range_array)
print("\n",linspace_array )

[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [0 2 4 6 8]

 [0.   0.25 0.5  0.75 1.  ]


In this example:

- **np.zeros((2, 3))** creates a 2x3 array filled with zeros.
- **np.ones((2, 3))** creates a 2x3 array filled with ones.
- **np.arange(0, 10, 2)** generates a 1D array with values from 0 to 10, stepping by 2.
- **np.linspace(0, 1, 5)** creates an array of 5 evenly spaced numbers between 0 and 1.


### Array Properties
You can check important properties of a NumPy array, such as its shape, size, and data type:

In [45]:
arr_2d.shape

(2, 3)

In [46]:
arr_2d.size

6

In [47]:
arr_2d.dtype

dtype('int64')

**This code retrieves:**

- The shape of the 2D array, which tells you the dimensions (rows and columns).
- The size of the array, indicating the total number of elements.
- The data type of the elements in the array, which shows the kind of data stored (e.g., integers, floats).

### Basic Arithmetic Operations

NumPy allows you to perform element-wise arithmetic operations on arrays:

In [49]:
# Element-wise addition
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

sum_array = arr_a + arr_b
print("Sum of Arrays:", sum_array)

# Element-wise multiplication
product_array = arr_a * arr_b
print("Product of Arrays:",product_array )

Sum of Arrays: [5 7 9]
Product of Arrays: [ 4 10 18]


In this example, we create *two 1D arrays*, **arr_a** and **arr_b**, and add them together. 

Also, we perform element-wise multiplication. Each element of **arr_a** is multiplied by the corresponding element of **arr_b**, resulting in a new array of products.

### NumPy Universal Functions

NumPy provides a variety of universal functions that operate element-wise on arrays. These functions include mathematical operations, trigonometric functions, and statistical calculations. Statistical functions are particularly useful for analyzing data and obtaining insights from numerical arrays.

- **Mean:** Calculates the average value of the array elements.
- **Median:** Finds the middle value when the elements are sorted.
- **Standard Deviation:** Measures the amount of variation or dispersion in the dataset.

Here’s how to use these functions:

In [35]:
data = np.array([1, 2, 3, 4, 5])

#Your code goes here

We can also find the minimum and maximum values in an array:

In [22]:
# Calculate minimum and maximum values
#Your code goes here

Also, we can compute the correlation coefficient between two datasets:

In [23]:
# Example arrays for correlation
#Your code goes here

# Calculate correlation coefficient
#Your code goes here

The correlation coefficient matrix shows the relationship between **arr_x** and **arr_y**. A value close to -1 indicates a strong negative correlation, while a value close to 1 indicates a strong positive correlation.

### Other Operations
#### Indexing

You can access individual elements of an array using indexing:

In [34]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
#Your code goes here

This code retrieves the first element of the 1D array **arr_1d** and the element located at row 1, column 2 in the 2D array **arr_2d**.

#### Slicing
Slicing allows you to access a subset of an array:

In [25]:
# Slicing a 1D array
#Your code goes here

This retrieves a slice of the 1D array, including elements from index 1 up to, but not including, index 4.

In [26]:
# Slicing a 2D array
#Your code goes here

Here, we extract the first row of the 2D array and the second column using slicing. The : operator means "select all elements in this dimension."

#### Reshaping Arrays
You can change the shape of an array without changing its data using the **reshape()** method:

In [27]:
#Your code goes here

In this code, we reshape the 1D array arr_1d into a 5x1 array. The total number of elements remains the same, but the structure changes.

#### Joining Arrays
NumPy allows you to **concatenate (join)** arrays using functions like **np.concatenate()**, **np.vstack()** (for vertical stacking), and **np.hstack()** (for horizontal stacking):

In [33]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Joining 1D arrays
#Your code goes here

Here, we concatenate **arr_a** and **arr_b** into a single 1D array containing all their elements.

In [32]:
# Joining 2D arrays
arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[5, 6], [7, 8]])

#Your code goes here

In this example, we create two 2D arrays and stack them vertically, resulting in a new array with four rows.

In [29]:
#Your code goes here

Similarly, we stack the two 2D arrays horizontally, which combines the columns.

#### Splitting Arrays
The **np.split()** function splits an array into multiple sub-arrays along a specified axis. The function takes two main arguments: the array to split and the number of splits you want to make.

In [31]:
# Create a 1D array
joined_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#Your code goes here

# Split the array into 2 equal parts
#Your code goes here

We create a **1D array**, joined_array, containing ten elements, and the **np.split(joined_array, 2)** function is used to split the array into two equal parts, resulting in a list of sub-arrays. 

It's important to note that if the number of elements in the original array is not evenly divisible by the number of splits specified, NumPy will raise a *ValueError*.